# Generated by Django 3.1.7 on 2021-03-30 07:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20210328_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserManager',
        ),
        migrations.RenameField(
            model_name='usermanager',
            old_name='user',
            new_name='userModel',
        ),
    ]
