# Generated by Django 3.1.7 on 2021-05-24 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=50, verbose_name='Nom')),
                ('type', models.CharField(default='Inconnu', max_length=50, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=50, verbose_name='Nom')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité')),
                ('price', models.IntegerField(default=0, verbose_name='Prix')),
                ('database', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='manager.database')),
            ],
        ),
    ]
